In [1]:
import cv2
import numpy as np
from skimage.feature import blob_dog

In [2]:
image = cv2.imread("C:/Users/islam/Desktop/Zuarbeit_Tarekul/DSC_0231.jpg")

In [3]:
# Convert the image to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

In [ ]:
edges = cv2.Canny(gray, 50, 155)

In [ ]:
cv2.imshow("Original", edges)
# cv2.imshow("edges", thresh)
cv2.waitKey(10000)
cv2.destroyAllWindows()

In [4]:
# Apply binary thresholding to create a binary mask
_, binary_mask = cv2.threshold(gray, 130, 255, cv2.THRESH_BINARY)

In [ ]:
# Define the kernel for the closing operation
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (22, 22))  # Adjust the kernel size as needed

# Apply the closing operation
closed_mask = cv2.morphologyEx(binary_mask, cv2.MORPH_CLOSE, kernel)

In [ ]:
# Display the result of the closing operation
cv2.imshow('Closed Mask', closed_mask)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
# cv2.imwrite("C:/Users/islam/Desktop/binary_mask.png", binary_mask)

In [ ]:
kernel = np.ones((3, 3), np.uint8)

In [ ]:
# a. Erosion (optional): To remove small noise or imperfections
eroded_mask = cv2.erode(dilated_mask, kernel, iterations=1)

In [ ]:
# Define the kernel for the opening operation
kernel_opening = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))  # Adjust the kernel size as needed

# Apply the opening operation
opened_mask = cv2.morphologyEx(closed_mask, cv2.MORPH_OPEN, kernel_opening)

In [ ]:
# Display the result of the closing operation
cv2.imshow('Opened Mask', opened_mask)
cv2.waitKey(10000)
cv2.destroyAllWindows()

In [ ]:
# b. Dilation: To enlarge the cross shapes and make them more prominent
dilated_mask = cv2.dilate(binary_mask, kernel, iterations=1)

In [9]:
lines = cv2.HoughLinesP(binary_mask, 0.5, np.pi / 180, 10, 50, 10 )
print(lines)

[[[2199 1080 2256 1128]]

 [[2371 1226 2417 1262]]

 [[2190 1079 2244 1133]]

 [[2195 1408 2212 1437]]

 [[2159 1600 2178 1573]]

 [[2116 1577 2129 1590]]

 [[2400 1247 2416 1224]]

 [[2364 1094 2369 1114]]

 [[2462 1528 2481 1503]]

 [[2332 1627 2337 1654]]

 [[2342 1654 2376 1721]]

 [[2234 1108 2254 1079]]

 [[2194 1409 2207 1431]]

 [[2192 1079 2248 1135]]

 [[2214 1137 2251 1075]]

 [[2205 1151 2224 1115]]

 [[2081 1127 2091 1144]]

 [[2115 1582 2171 1631]]

 [[2339 1650 2343 1669]]

 [[2377 1233 2421 1270]]

 [[2366 1094 2371 1113]]

 [[2357 1665 2382 1629]]

 [[2472 1507 2490 1483]]

 [[2140 1608 2170 1636]]

 [[2480 1494 2492 1477]]

 [[2319 1726 2352 1677]]

 [[2196 1151 2211 1125]]

 [[2115 1578 2128 1591]]

 [[2193 1079 2226 1109]]

 [[2244 1076 2246 1089]]

 [[2230 1116 2253 1134]]

 [[2317 1508 2320 1528]]

 [[2348 1689 2360 1671]]

 [[2230 1109 2257 1131]]

 [[2330 1649 2330 1627]]

 [[2190 1080 2225 1115]]

 [[2198 1409 2224 1377]]

 [[2478 1509 2483 1526]]

 [[2357 1662

In [ ]:
pip install shapely

In [6]:
from shapely.geometry import LineString
shapely_lines = []
for line in lines:
    start_point = (line[0][0], line[0][1])
    end_point = (line[0][2], line[0][3])
    shapely_lines.append(LineString([start_point, end_point]))
    print(shapely_lines)

[<LINESTRING (2199 1080, 2256 1128)>]
[<LINESTRING (2199 1080, 2256 1128)>, <LINESTRING (2371 1226, 2417 1262)>]
[<LINESTRING (2199 1080, 2256 1128)>, <LINESTRING (2371 1226, 2417 1262)>, <LINESTRING (2190 1079, 2244 1133)>]
[<LINESTRING (2199 1080, 2256 1128)>, <LINESTRING (2371 1226, 2417 1262)>, <LINESTRING (2190 1079, 2244 1133)>, <LINESTRING (2195 1408, 2212 1437)>]
[<LINESTRING (2199 1080, 2256 1128)>, <LINESTRING (2371 1226, 2417 1262)>, <LINESTRING (2190 1079, 2244 1133)>, <LINESTRING (2195 1408, 2212 1437)>, <LINESTRING (2159 1600, 2178 1573)>]
[<LINESTRING (2199 1080, 2256 1128)>, <LINESTRING (2371 1226, 2417 1262)>, <LINESTRING (2190 1079, 2244 1133)>, <LINESTRING (2195 1408, 2212 1437)>, <LINESTRING (2159 1600, 2178 1573)>, <LINESTRING (2116 1577, 2129 1590)>]
[<LINESTRING (2199 1080, 2256 1128)>, <LINESTRING (2371 1226, 2417 1262)>, <LINESTRING (2190 1079, 2244 1133)>, <LINESTRING (2195 1408, 2212 1437)>, <LINESTRING (2159 1600, 2178 1573)>, <LINESTRING (2116 1577, 2129 15

In [7]:
for i in range(len(shapely_lines)):
    for j in range(i + 1, len(shapely_lines)):
        intersection = shapely_lines[i].intersection(shapely_lines[j])
        if not intersection.is_empty:  # Check if lines actually intersect
            if intersection.geom_type == 'Point':
                print(f"Lines {i} and {j} intersect at: {intersection.coords[0]}")
            else:
                print(f"Lines {i} and {j} have an overlapping segment: {intersection}")

Lines 0 and 14 intersect at: (2231.6220338983053, 1107.471186440678)
Lines 0 and 132 intersect at: (2232.4906666666666, 1108.2026666666666)
Lines 2 and 14 intersect at: (2226.7070707070707, 1115.7070707070707)
Lines 6 and 106 intersect at: (2401.058365758755, 1245.4785992217899)
Lines 8 and 85 intersect at: (2475.4968287526426, 1510.2410147991543)
Lines 8 and 112 intersect at: (2476.5604575163397, 1508.8415032679738)
Lines 10 and 32 intersect at: (2354.677966101695, 1678.9830508474577)
Lines 13 and 14 intersect at: (2227.4545454545455, 1114.4545454545455)
Lines 14 and 29 intersect at: (2245.312396694215, 1084.5305785123967)
Lines 14 and 33 intersect at: (2230.4774919614147, 1109.3890675241157)
Lines 14 and 99 intersect at: (2229.7283800243604, 1110.644336175396)
Lines 19 and 76 intersect at: (2397.659075686537, 1250.372404554588)
Lines 32 and 62 intersect at: (2355.5922330097087, 1677.611650485437)
Lines 76 and 92 intersect at: (2398.6388888888887, 1248.638888888889)
Lines 83 and 85 in

In [8]:
# Draw lines on the image
for line in lines:
    x1, y1, x2, y2 = line[0]
    cv2.line(image, (x1, y1), (x2, y2), (0, 255, 0), 2)

# Display the image
cv2.imshow('Image with Lines, Intersections, and Text', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
# Draw circles at intersection points on the original image
for i in range(len(shapely_lines)):
    for j in range(i + 1, len(shapely_lines)):
        intersection = shapely_lines[i].intersection(shapely_lines[j])
        if not intersection.is_empty:
            if intersection.geom_type == 'Point':
                x, y = map(int, intersection.coords[0])
                cv2.circle(image, (x, y), 2, (0, 0, 255), -1)  # Draw a red filled circle
                cv2.putText(image, f'({x}, {y})', (x + 10, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 1, cv2.LINE_AA)
            else:
                # In case of overlapping segments, you might want to handle differently
                pass

# Show or save the image with circles drawn at intersection points
cv2.imshow('Intersections', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
if intersection.geom_type == 'Point':
    x, y = intersection.coords[0]
    x, y = int(x), int(y)  # Convert to integers 
    cv2.circle(image, (x, y), radius=3, color=(0, 0, 255), thickness=-1) 

In [ ]:
if intersection.geom_type == 'LineString':
    for x, y in intersection.coords:
        x, y = int(x), int(y)  
        cv2.circle(image, (x, y), radius=1, color=(0, 0, 255), thickness=-1)

In [ ]:
# Extract line coordinates
x1, y1, x2, y2 = lines.squeeze().T

# Calculate lengths using Euclidean distance
lengths = np.sqrt(((x2 - x1) ** 2) + ((y2 - y1) ** 2))

# Sort lines and lengths together by length in descending order
sorted_lines_lengths = sorted(zip(lines, lengths), key=lambda x: x[1], reverse=True)

# Print sorted lines and lengths
print("Lines sorted from longest to shortest:")
for line, length in sorted_lines_lengths:
    print(f"Line: {line}, Length: {length:.2f}")

In [ ]:
import numpy as np

def line_intersection(line1, line2):
    """Calculates intersection point lines (if it exists).

    Args:
        line1: Line represented as a list or tuple: [(x0, y0), (x1, y1)]
        line2: Line represented similarly.

    Returns:
        intersection_point: A tuple (x, y) if intersection exists, otherwise None
    """
    (x0, y0), (x1, y1) = line1[0]
    (x2, y2), (x3, y3) = line2[0]

    dx1 = x1 - x0
    dy1 = y1 - y0
    dx2 = x3 - x2
    dy2 = y3 - y2

    det = dx1 * dy2 - dy1 * dx2
    if det == 0: 
        return None  # Lines are parallel or coincident

    t1 = ((x2 - x0) * dy2 + (y0 - y2) * dx2) / det 
    t2 = ((x2 - x0) * dy1 + (y0 - y2) * dx1) / -det  

    # Check if intersection lies within line segments
    if 0 <= t1 <= 1 and 0 <= t2 <= 1:
        intersection_x = x0 + t1 * dx1  
        intersection_y = y0 + t1 * dy1
        return intersection_x, intersection_y
    else:
        return None

In [ ]:
for i in range(len(lines) - 1):
    for j in range(i + 1, len(lines)):
        intersection_point = line_intersection(lines[i], lines[j])
        if intersection_point is not None:
            print(f"Intersection between lines {i} and {j}: {intersection_point}")

In [ ]:
def calculate_intersection(p1, p2, p3, p4):
    """
    Calculates the intersection point of two lines using their slope-intercept form.

    Args:
        p1, p2: Coordinates of two points on the first line.
        p3, p4: Coordinates of two points on the second line.

    Returns:
        The intersection point (x, y) if they intersect, None otherwise.
    """

    # Get slopes and y-intercepts of both lines
    x1, y1 = p1
    x2, y2 = p2
    m1 = (y2 - y1) / (x2 - x1) if x2 - x1 != 0 else float('inf')  # Handle vertical line
    b1 = y1 - m1 * x1

    x3, y3 = p3
    x4, y4 = p4
    m2 = (y4 - y3) / (x4 - x3) if x4 - x3 != 0 else float('inf')  # Handle vertical line
    b2 = y3 - m2 * x3

    # Check for parallel or coincident lines
    if m1 == m2 and b1 == b2:
        return None  # Lines are coincident, infinite intersections

    elif m1 == m2 and b1 != b2:
        return None  # Lines are parallel, no intersection

    # Calculate intersection point
    if m1 != float('inf') and m2 != float('inf'):  # Both lines have finite slopes
        x = (b2 - b1) / (m1 - m2)
        y = m1 * x + b1
    elif m1 == float('inf'):  # First line is vertical
        x = x1
        y = m2 * x + b2
    else:  # Second line is vertical
        x = x3
        y = m1 * x + b1

    return (x, y)

In [ ]:
# Create empty lists to store points
line_points = []
intersections = []

# Extract points and calculate intersections (loop through detected lines)
for line in lines:
    x1, y1, x2, y2 = line[0]  # Access line endpoints from each line
    line_points.append([(x1, y1), (x2, y2)])  # Append as pairs to list

    # Calculate intersection with other lines (assuming 3 lines)
    if len(line_points) >= 4:
        for other_line in line_points[:2]:
            intersection = calculate_intersection(other_line[0], other_line[1], (x1, y1), (x2, y2))
            if intersection:
                intersections.append(intersection)

In [ ]:
print(intersections)

In [ ]:
def find_close_point_centroids(points, threshold):
    close_points = {}
    for i in range(len(points)):
        for j in range(i + 1, len(points)):
            distance = np.sqrt(((points[i][0] - points[j][0])**2) + ((points[i][1] - points[j][1])**2))
            if distance <= threshold:
                if i in close_points:
                    close_points[i].append(points[j])
                elif j in close_points:
                    close_points[j].append(points[i])
                else:
                    close_points[i] = [points[i], points[j]]

    centroids = {}
    for group_id, group in close_points.items():
        centroid_x = sum(point[0] for point in group) / len(group)
        centroid_y = sum(point[1] for point in group) / len(group)
        centroids[group_id] = (centroid_x, centroid_y)

    return centroids

In [ ]:
threshold = 10 # Adjust based on your image scale
centroids = find_close_point_centroids(intersections, threshold)
print(centroids)

In [ ]:
for point in line_points:
    cv2.line(image, point[0], point[1], (0, 255, 0), 2)
for key, point in centroids.items():
    x, y = point  # Extracting x and y coordinates from the tuple

    # Draw circle and add text label
    cv2.circle(image, (int(x), int(y)), 5, (255, 0, 0), -1)
    cX, cY = int(x), int(y)  # Use integer coordinates for drawing text
    cv2.putText(image, f"({cX}, {cY})", (cX - 20, cY - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1)

# for key, point in centroids.items():
#     x, y = point  # Extracting x and y coordinates from the tuple
#     cv2.circle(image, (int(x), int(y)), 3, (255, 0, 0), -1)
# for point in centroids.items():
#      cv2.circle(image, (int(point[0]), int(point[1])), 5, (255, 0, 0), -1)q 

In [ ]:
cv2.imshow("Results", image)
if cv2.waitKey(60000) & 0xFF == ord("q"):  # Check for 'q' press to close manually
    cv2.destroyAllWindows()
else:
    cv2.destroyAllWindows()

In [ ]:
# Convert masks to BGR for visualization (if necessary)
# eroded_mask_vis = cv2.cvtColor(eroded_mask, cv2.COLOR_GRAY2BGR)  # Assuming eroded_mask is grayscale
dilated_mask_vis = cv2.cvtColor(dilated_mask, cv2.COLOR_GRAY2BGR)  # Assuming dilated_mask is grayscale

# Display the masks in separate windows
# cv2.imshow("Original Mask", binary_mask)
# cv2.imshow("Eroded Mask (1 iteration)", eroded_mask_vis)
cv2.imshow("Dilated Mask (1 iteration)", dilated_mask_vis)

# Wait for a key press or window closure to exit
while True:
    if cv2.waitKey(15000) == ord("q") or not cv2.getWindowProperty("Original Mask", 0):
        break

# Close all windows
cv2.destroyAllWindows()

In [ ]:
# Display the binary mask
try:
    cv2.imshow('Binary Mask', binary_mask)
    cv2.waitKey(30000)
    cv2.destroyAllWindows()
except Exception as e:
    print("An error occurred:", e)

In [ ]:
# Find blobs (bright spots) in the image
blobs = blob_dog(binary_mask, threshold=0.5)
print(blobs)

In [ ]:
# Get the coordinates of the centers of the blobs
blob_centers = blobs[:, :2]
print(blob_centers)

In [ ]:
# Print the coordinates of the blobs
for i, blob in enumerate(blob_centers):
    print(f"Blob {i+1} coordinates: ({blob[0]}, {blob[1]})")

In [ ]:
# Draw blob coordinates on the image
for i, blob in enumerate(blob_centers):
    x, y = int(blob[0]), int(blob[1])
    
    cv2.circle(image, (x, y), 3, (0, 0, 255), -1)
    #cv2.putText(image, f"Blob {i+1}: ({x}, {y})", (x, y), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)

In [ ]:
# Display the image with coordinates
cv2.imshow('Blobs with Coordinates', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# Find contours in the mask
contours, hierarchy = cv2.findContours(dilated_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

In [ ]:
print(contours)

In [ ]:
# Iterate through contours and print their lengths
for i, contour in enumerate(contours):
    contour_length = len(contour)
    print(f"Contour {i+1} length: {contour_length}")

In [ ]:
# Filter contours based on the number of coordinates
filtered_contours = [contour for contour in contours if len(contour) > 11]

In [ ]:
# Iterate through each contour
for contour in filtered_contours:
    # Calculate the centroid of the contour
    M = cv2.moments(contour)
    if M["m00"] != 0:
        cX = int(M["m10"] / M["m00"])
        cY = int(M["m01"] / M["m00"])
        print(cX, cY)
    else:
        cX, cY = 0, 0

    # Draw a circle at the centroid
    cv2.circle(image, (cX, cY), 3, (0, 0, 255), -1)
    # Put text with coordinates
    cv2.putText(image, f'({cX}, {cY})', (cX - 20, cY - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.3, (255, 255, 255), 1)

In [ ]:
# Display the image with centroids
cv2.imshow('Centroids', image)
cv2.waitKey(100000)
cv2.destroyAllWindows()